### PR TITLE
Restaurant Page

### PR DESCRIPTION
**Pull request by KumarAmitt**
**Major Implementations**

-- Configure Webpack 
-- Use only JavaScript to generate the HTML and append contents inside it

**KEY NOTE**
-- Please refer to the bottom of this [article](https://www.freecodecamp.org/news/javascript-modules-a-beginner-s-guide-783f7d7a5fcc/)  for ES6 module implementations.

-- Please read the following instructions for linter related modifications as suggested in documentation:

1. In the file .github/workflows/linters.yml line 48 replace "**/*.{css,scss}" with "**/*.scss"

2. Use npx stylelint "**/*.scss" to lint you SCSS files and not the generated CSS

All the feedback and suggestions to improve this project will be highly valuable.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑**

Hello @KumarAmitt ,
First of all congrats on this project. I am really proud of the work you made👏👏👏
kudos👌👌. The way you divided your codes is impressive.

Let's make some changes and make this work impeccable.

[REQUIRED]: Kindly change your files into modules. Here is how to create a module.
`const module_name = (() => {
   const function_name = () => {}
   return {function_name};
})();`

This will allow better and organized codes.

[REQUIRED]: Kindly make sure you used only ES6 codes. In your nav.js, you used a function keyword. Kindly change it to an arrow function.

That's it
giphy (2)

Make the requested changes and ask for another review.👍👍
Happy coding💻💻💻

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi @KumarAmitt :wave: 

After going through the functions you implemented, you are yet to implement a module.

Kindly go through this [article](https://www.freecodecamp.org/news/javascript-modules-a-beginner-s-guide-783f7d7a5fcc/)
Also [watch this lesson](https://classroom.udacity.com/courses/ud711/lessons/75276e41-b4b7-462c-881b-bf465f28485b/concepts/50d77c45-73f6-41a9-b6bf-88ccde54db81) on udacity.

That's it, make the update then submit another form for a code review.


### Happy coding :technologist: 

#### ``` Uchechukwu Henry Inyama ```

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Amit Kumar** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
One last detail to improve before you can go ahead:

- [ ] Don't edit the linter.yml file. Check out the original: https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Amit Kumar** 
You are almost there project :muscle:  :muscle:
One last detail to improve before you can go ahead:

- [ ] Your linters.yml file and the original doesn't match. Check out the original: https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by voscarmv — APPROVED** [review]
# Project status: Approved 💯 ✨ 😎 👍 
### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
